UCBerkeleySETI/turbo_seti

- Dockerfile
- turbo_seti/findoppler/data_handler.py
- turbo_seti/findoppler/find_candidates.py
- turbo_seti/findoppler/findopp.py
- turbo_seti/findoppler/fits_wrapper.py
- turbo_seti/findoppler/plot_candidates.py
- turbo_seti/findoppler/seti_event.py
Will require some testing before being merged into main branch.
* Did a global search for `print '$'` and replaced with `print('$')`, which will help Py3 (assuming we decide to support it!)
* filterbank / hdf5 recognition wasn't working at Parkes as file ending is .h5. Changed to use `h5py.is_hdf5` to detect the HDF5 signature. Also now using a `is_filterbank` function in blimpy that was added recently. *Note: this means blimpy needs to be upgraded for this version of turbo_seti to run*
> Toward Py3 compatibility

- turbo_seti/__init__.py
- turbo_seti/findevent/find_scan_sets.py
This is so you can do:
```python
import turbo_seti
turbo_seti.__version__
```
It gets the version from setup.py
> Add __version__ information to __init__.py

- turbo_seti/findoppler/data_handler.py
- turbo_seti/findoppler/seti_event.py
The changes here are just some comments in 2 files, and one code change, which is the optimization fix I mentioned on slack.
> Data Handler Optimization and Comments

- setup.py
- turbo_seti/findoppler/data_handler.py
- turbo_seti/findoppler/findopp.py
- turbo_seti/findoppler/seti_event.py
Should fix #26, but only really a short-term solution.
> Fix for obs_info=None

- turbo_seti/find_event/find_event.py
- turbo_seti/find_event/find_event_pipeline.py
- Create work around for sources with the name format `B'<sourcename>'`
- Fix the import of `find_event` in `find_event_pipeline`
> Fix minor bugs

- test/test_turbo_seti.py
- turbo_seti/find_doppler/file_writers.py
Pylint fixes:
* Removed imports and calculations which were not used.
* Reordered imports of packages as follows: (a) system packages, (b) pypi packages, (c) SETI imports.
I did not apply pylint recommendations concerning purely style changes.  I created enough reviewer work.
> Issues #59 & 62 + fix some (not all) pylint remarks + tidy up

- turbo_seti/find_doppler/data_handler.py
- turbo_seti/find_doppler/find_doppler.py
- turbo_seti/find_doppler/helper_functions.py
- turbo_seti/find_doppler/taylor_tree.pyx
Sole functional changes: remove unused size_limit parameter and related comments.
The other modifications were as a result of pylint.
Tested with pytest and turboSETI.
> Issues #61, #64, and #65

- test/test_plotting.py
- test/test_turbo_seti.py
- turbo_seti/find_event/find_event.py
- turbo_seti/find_event/plot_event.py
Expanded coverage with respect to the turbo_seti/find_events folder and test folder.
Contents:
* Fix-ups for plot_event.py
* test_turbo_seti.py now has a test_make_waterfall_plots() function that works
* New test_plotting.py program
Special thanks: 
@mattlebofsky for very responsive testing HDF5 file support
@ssmith00 for doing a great job in many ways for the last few days
> A contribution towards issue #75

- .travis.yml
- test/test_turbo_seti.py
- turbo_seti/find_doppler/data_handler.py
Copied from Dockerfile: ```pip install git+https://github.com/ucberkeleyseti/blimpy```
Hopefully, processing for the requirements.txt entry for blimpy will simply end in "already installed".
If successful, then turbo_seti PRs will always get an accurate coverage map.
> Use blimpy on github instead of installing from pypi

- turbo_seti/find_doppler/find_doppler.py
> Fix drift_block conditional statement.

- turbo_seti/find_event/find_event.py
Fix issue #115 - find_events() is not handling a nil OFF hit table list correctly
> Issue #115

- VERSION-HISTORY.md
- setup.py
- turbo_seti/find_doppler/data_handler.py
- turbo_seti/find_doppler/find_doppler.py
Fix issue #135 by reverting changes made by PR #121 and #113.
> Fix issue #135 by reverting changes made by PR #121 and #113.

- turbo_seti/find_event/plot_event.py
The test/run_tests.sh file has already been updated to specify ```pytest -s```.
> Issue #138 - plot_event.py portion

- setup.py
- test/test_turbo_seti.py
- turbo_seti/find_doppler/find_doppler.py
Changes:
* setup.py :: version 2.0.4 --> 2.0.4.1
* turbo_seti/find_doppler/find_doppler.py :: Issue #141
* test/test_turbo_seti.py :: adjusted for fixes to find_doppler.py
> Fix issue #141 and side effects in test_turbo_seti.py

- VERSION-HISTORY.md
- setup.py
- turbo_seti/find_event/plot_event.py
Included is a change to test_pipelines.py: use the Voyager 2020 data set.  This test will be expanded soon to validate the CSV entries.
Bump version to 2.0.6.
> Fix issue #152 - plot_event.py 

- VERSION-HISTORY.md
- setup.py
- turbo_seti/find_doppler/data_handler.py
- turbo_seti/find_doppler/find_doppler.py
- turbo_seti/find_doppler/kernels/__init__.py
- turbo_seti/find_doppler/kernels/_hitsearch/__init__.py
- turbo_seti/find_doppler/kernels/_hitsearch/kernels.cu
This pull-request reverts the code-structure changes inside the main loop of `search_coarse_channel` method introduced by version 2.0.0. This code was to blame for several bugs.
Note that the GPU and NUMBA kernel code is still in use.
This PR specifically fixes issues #135 and #141.
> Reverting code-structure changes to the main loop.

- VERSION-HISTORY.md
- setup.py
- turbo_seti/find_doppler/find_doppler.py
- turbo_seti/find_doppler/merge_dats_logs.py
- turbo_seti/find_doppler/seti_event.py
* find_doppler.py: mostly search_coarse_channel()
* seti_event.py: add min_drift parameter.
* merge_dats_logs.py: create a top hit numbering in the merged DAT file and fix the DAT output line formatting.
* setup.py: bump version.
* VERSION-HISTORY.md: note all of this for version 2.0.8.
> Version 2.0.8 - Fix issues #89, #178, and #179

- test/test_find_event.py
test_find_event.py is added to the ```test``` subdirectory.
> Address issue #185

- VERSION-HISTORY.md
- setup.py
- test/test_pipelines_2.py
- turbo_seti/find_doppler/find_doppler.py
Issue #213 - Doppler search dies when using GPU (string format issue).
Issue #214 - Need some testing for plot_dir parameter of plot_event_pipeline.
> Fix issues #213 and #214

- VERSION-HISTORY.md
- setup.py
- turbo_seti/find_doppler/data_handler.py
- turbo_seti/find_doppler/find_doppler.py
* Fix issue #238 - make sure that ```n_coarse_chan``` is logged correctly in all cases.
* Remove duplicate logging.
* Re-order and reformat some of the preamble logging.
> Fix issue #238 and streamline logging

- VERSION-HISTORY.md
- setup.py
- turbo_seti/find_doppler/data_handler.py
- turbo_seti/find_doppler/find_doppler.py
- turbo_seti/find_doppler/helper_functions.py
- turbo_seti/find_doppler/seti_event.py
> Miscellaneous cleanup of 26 June 2021

- turbo_seti/find_doppler/find_doppler.py
- turbo_seti/find_doppler/seti_event.py
Merge in Danny's documentation uodate.
> Updating documentation re #221

- VERSION-HISTORY.md
- setup.py
- test/test_find_event.py
- test/test_pipelines_3.py
- test/test_turbo_seti.py
- turbo_seti/find_doppler/data_handler.py
- turbo_seti/find_doppler/file_writers.py
- turbo_seti/find_doppler/find_doppler.py
- turbo_seti/find_event/find_event.py
See https://github.com/UCBerkeleySETI/turbo_seti/issues/231 for discussion and remediation details.
> Correct find_event.py calc_freq_range() issue #231

- .gitignore
- VERSION-HISTORY.md
- turbo_seti/find_doppler/data_handler.py
- turbo_seti/find_doppler/find_doppler.py
- turbo_seti/find_doppler/kernels/__init__.py
- turbo_seti/find_doppler/seti_event.py
This PR makes enhancements to the GPU mode. I measured 57% performance uplift with the `Parkes_57941_12846_HIP33499` file.
> Enhanced GPU mode

- .gitignore
- VERSION-HISTORY.md
- turbo_seti/find_doppler/data_handler.py
- turbo_seti/find_doppler/find_doppler.py
- turbo_seti/find_doppler/kernels/__init__.py
- turbo_seti/find_doppler/seti_event.py
This PR addresses #254. Not tested with multiple GPUs.
```shell
$ turboSETI [FILE] --gpu y --gpu_id 0
```
> Add GPU device selection with cli argument gpu_id.

- VERSION-HISTORY.md
- setup.py
- test/test_turbo_seti.py
- turbo_seti/find_doppler/find_doppler.py
- turbo_seti/find_doppler/seti_event.py
Default GPU precision to 32-bit (single-precision).
> More GPU Performance Improvements

- VERSION-HISTORY.md
- setup.py
- turbo_seti/find_doppler/data_handler.py
> Fix crash in conversion of a 59 GiB filterbank file

- VERSION-HISTORY.md
- setup.py
- turbo_seti/find_doppler/kernels/_hitsearch/__init__.py
GPU fix: turbo_seti-master/turbo_seti/find_doppler/kernels/_hitsearch/__init__.py
Change cp._core.core.ndarray
to cp.ndarray
everywhere.
> Fix issue #272 (GPU-related)

- VERSION-HISTORY.md
- setup.py
- test/test_turbo_seti.py
- turbo_seti/find_doppler/data_handler.py
- turbo_seti/find_doppler/file_writers.py
- turbo_seti/find_doppler/find_doppler.py
- turbo_seti/find_doppler/helper_functions.py
> Fix source code variable names in subdirectory find_doppler

- VERSION-HISTORY.md
- docs/conf.py
- setup.py
This pull request addresses the reference between the documentation and the code. The Read the Docs documentation should now have a link for the source code.
> Add source reference to the Read the Docs documentation.

- VERSION-HISTORY.md
- setup.py
- turbo_seti/find_event/run_pipelines.py
**Sample shell script**
```
H5_DIR=/home/elkins/BASIS/seti_data/voyager_2020/
OUT_SEARCH=/home/elkins/BASIS/seti_data/voyager_2020/out_search
OUT_PIPELINES=/home/elkins/BASIS/seti_data/voyager_2020/out_pipelines
FILTER_THRESHOLD=3
for FILE in ${H5_DIR}/*.h5
do
echo "===== Running turboSETI on HDF5: $FILE ....."
turboSETI -s 30 -M 4 $FILE -o $OUT_SEARCH
done
echo
echo "===== Running plotSETI ====="
plotSETI --filter_threshold $FILTER_THRESHOLD --dat_dir $OUT_SEARCH --out_dir $OUT_PIPELINES `pwd`
```
Sample standard output is attached
[stdout.log](https://github.com/UCBerkeleySETI/turbo_seti/files/7655901/stdout.log)
.
> plotSETI with .h5 files and .dat files in separate directories

- VERSION-HISTORY.md
- requirements.txt
- setup.py
- turbo_seti/find_doppler/data_handler.py
- turbo_seti/find_event/find_event_pipeline.py
> Fix data_handler.py and find_event_pipeline.py mangling of .h5 and .dat file names

- VERSION-HISTORY.md
- setup.py
- turbo_seti/find_doppler/find_doppler.py
* Show versions of hdf5plugin and the HDF5 library.
* Enable the display of HDF5 library error messages which are inhibited by default.
> Enhance logged information

- turbo_seti/find_doppler/kernels/_taylor_tree/_core_cuda.py
@fantonio2 politely requests to be credited for the kernel in the code. A small comment-only change so I don't think it requires a separate release
> Add comment crediting Franklin
